apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-configmap-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
data:
  testprop: {{ .Values.testmap.testprop }}
  hello: world
  bull: sh*t

